language: android

android:
  components:
  - tools
  - platform-tools
  - extra
  - build-tools-25.0.1
  - android-25

jdk:
- oraclejdk8

before_install:
- nvm install 6

install:
- npm install -g cordova gulp
- npm install
- gulp install

script:
- gulp dist
- cordova platform add android
- cordova build android
